AWSTemplateFormatVersion: '2010-09-09'
Transform: Taimos-Fargate
Description: Deploy a service on AWS Fargate
Parameters:
  Count:
    Type: String
    Description: The number of instances
Resources:
  TestService:
    Type: Taimos::FargateService
    Properties:
      BaseStack: Fargate-Test
      Name: TestService
      Image: nginx:latest
      Port: 80
      Size:
        Cpu: 256
        Memory: 512
        Count: !Ref Count
      Subdomain: test
      DeregistrationDelay: '0'
      HealthCheck:
        Path: /
        Status: '200'
      Policies:
        - PolicyName: test-service
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 's3:PutObject'
              Resource: '*'
      Environment:
        FOO: bar